const languages = {
    es: {
        
        home: "Inicio",
        products: "Productos",
        erp_pymes: "ERP PyMEs",
        erp_vehicles: "ERP Vehículos",
        about_us: "Nosotros",
        contact: "Contacto",
        register: "Registro",
        login: "Ingreso",
        hero_title: "<strong>Lutente ERP</strong> es",
        hero_subtitle: "la solución que <strong>NECESITAS</strong>",
        learn_more: "Conocer más",
        section_1_title: "Toda tu empresa en un solo Sistema de Gestión",
        section_1_subtitle: "Nuestro sistema de gestión en la nube está diseñado para simplificar y optimizar la operación de tu empresa.",
        section_2_title: "ES HORA DE ADQUIRIR NUESTRO ERP",
        centralize_data: "CENTRALIZA TUS DATOS",
        centralize_text: "Con un ERP, toda la información crucial de tu negocio (inventarios, finanzas, ventas, etc.) estará integrada en un solo sistema, ¡facilitando el acceso y análisis de datos!.",
        optimize_processes: "OPTIMIZA TUS PROCESOS",
        optimize_text: "Las funciones automatizadas de un ERP se encargan de las tareas tediosas, permitiéndote concentrarse en el crecimiento de su negocio.",
        increase_efficiency: "AUMENTA LA EFICIENCIA",
        efficiency_text: "Al eliminar procedimientos manuales y errores humanos, un ERP aumentará drásticamente la productividad de tus operaciones.",
        reasons_to_choose_us: "RAZONES PARA ELEGIRNOS",
        global_access: "ACCESO GLOBAL E INSTANTÁNEO",
        global_access_text: "LA NUBE TE PERMITE ACCEDER A TUS DATOS DE FORMA REMOTA, LO QUE TE BRINDA LA LIBERTAD DE TRABAJAR DESDE CASA, MIENTRAS VIAJAS, O INCLUSO DE DIFERENTES UBICACIONES, CON INFORMACIÓN ACTUALIZADA EN TIEMPO REAL.",
        security: "SEGURIDAD Y PROTECCIÓN DE DATOS",
        security_text: "AL ACTUALIZAR LA PLATAFORMA EN LA NUBE PUEDES ESTAR TRANQUILO SABIENDO QUE TUS DATOS ESTÁN PROTEGIDOS DE FORMA ROBUSTA, RESGUARDADOS CONTRA PERDIDAS, ROBOS O INCONVENIENTES GRACIAS A RESPALDOS DIARIOS DE TODA LA INFORMACIÓN.",
        scalability: "ESCALABILIDAD Y FLEXIBILIDAD",
        scalability_text: "CON ESTA HERRAMIENTA PUEDES ESCALAR FÁCILMENTE TUS RECURSOS SEGÚN LA DEMANDA DE TU EMPRESA. SI TU NEGOCIO CRECE SIMPLEMENTE PUEDES AMPLIAR EL ALMACENAMIENTO Y LA CAPACIDAD DE PROCESAMIENTO EN LA NUBE, SIN LA NECESIDAD DE ADQUIRIR UN NUEVO HARDWARE O REALIZAR COSTOSAS ACTUALIZACIONES.",
        cost_reduction: "REDUCCIÓN DE COSTOS",
        cost_reduction_text: "LA IMPLEMENTACIÓN DE LA PLATAFORMA EN LA NUBE PUEDE GENERAR AHORROS SIGNIFICATIVOS DE COSTOS. NO TENDRÁS QUE INVERTIR EN COSTOSOS SERVIDORES, NI EN SU MANTENIMIENTO DIARIO. TAMPOCO DEBERÁS REALIZAR LA COPIA MANUAL DE DATOS PERIÓDICAMENTE.",
        automotive_solution: "Solución Automotor",
        lutente_cars: "Lutente Autos",
        car_solution_text: "El sistema de gestión orientado a concesionarias y agencias de vehículos.",
        contact_us: "Contáctenos",
        
        hero_title_erp: "Lutente ERP",
        hero_subtitle_erp: "Toda tu empresa en un solo Sistema de Gestión",
        request_demo: "Solicitar DEMO",
        our_modules: "Nuestros Módulos",
        analytics: "ANALÍTICOS",
        analytics_desc: "Monitorea ventas, costos y rendimiento en tiempo real.",
        inventory: "INVENTARIOS",
        inventory_desc: "Mantén un control preciso y óptimo actualizado de tu stock.",
        administration: "ADMINISTRACIÓN",
        administration_desc: "Automatiza tareas y optimiza los procesos operativos de tu empresa.",
        purchases: "COMPRAS",
        purchases_desc: "Administra tus órdenes de compra de forma rápida y sencilla.",
        sales: "VENTAS",
        sales_desc: "Gestiona todo el proceso de venta desde un solo lugar.",
        optimize_company: "Optimizá tu empresa con nuestro <strong>ERP</strong>.",
        system_description: "Nuestro sistema es Moderno, Intuitivo para el usuario y Optimizado para un máximo rendimiento.",
        benefits: "<strong>BENEFICIOS</strong>",
        benefit_1_erp: "Digitalización y centralización de datos.",
        benefit_2_erp: "Control y automatización de movimientos y caja.",
        benefit_3_erp: "Facturación electrónica inmediata.",
        benefit_4_erp: "Integraciones con tiendas on-line.",
        benefit_5_erp: "Categorización de gastos y asientos contables.",
        benefit_6_erp: "Soporte y asesoramiento personalizado.",
        benefit_7_erp: "Mejor experiencia al usuario.",
        digital_transformation: "Evoluciona tu empresa con una <strong>Transformación Digital</strong>.",
        improve_business: "Mejora tu negocio",
        cloud_benefits: "Lutente Cloud te permite gestionar la operación de manera EFICIENTE y SIMPLE, utilizando IA maximizando el crecimiento de TU empresa",
        copyright: "®Lutente 2023",

        lutente_cloud_desc: "Lutente Cloud permite a concesionarias y agencias de vehículos a gestionar todas las áreas de la empresa con mayor eficiencia y velocidad.",
        request_demo: "Solicita DEMO",
        enter_demo: "Entrar DEMO",
        modules: "Módulos",
        benefits: "Beneficios",
        benefit_1: " Visibilidad y toma de decisiones",
        benefit_2: " Digitalización y centralización de datos",
        benefit_3: " Gestión: inventario, ventas, prendas, clientes, proveedores, trámites y gastos",
        benefit_4: " Control y automatización de movimientos y caja",
        benefit_5: " Control de flujo de efectivo, cheques y pagarés",
        benefit_6: " Mejor experiencia para el cliente",
        benefit_1_cons: "✔  Visibilidad y toma de decisiones",
        benefit_2_cons: "✔  Digitalización y centralización de datos",
        benefit_3_cons: "✔  Gestión: inventario, ventas, prendas, clientes, proveedores, trámites y gastos",
        benefit_4_cons: "✔  Control y automatización de movimientos y caja",
        benefit_5_cons: "✔  Control de flujo de efectivo, cheques y pagarés",
        benefit_6_cons: "✔  Mejor experiencia para el cliente",

        lutente_cloud_desc: "Lutente Cloud permite a concesionarias y agencias de vehículos a gestionar todas las áreas de la empresa con mayor eficiencia y velocidad.",
    request_demo: "Solicita DEMO",
    enter_demo: "Entrar DEMO",
    modules: "Modulos",
    inventory_module: "INVENTARIO",
    inventory_desc: "Inventario de vehículos. Integración con InfoAutos. Fácil ingreso/egreso. Fácil actualizacion de precios.",
    sales_module: "VENTAS",
    sales_desc: "Cierre e Historial de Ventas. Créditos Prendarios. Clientes.",
    admin_module: "ADMINISTRACIÓN",
    admin_desc: "Seguimiento Post Venta. Caja. Proveedores. Transacciones/ Movimientos. Asignación de trámites. Gastos.",
    registry_module: "GESTORÍA",
    registry_desc: "Trámites. Recepción. Preparación. Presentación Administración. Seguimiento. Retiro y cierre.",
    analytics_module: "ANALÍTICOS",
    analytics_desc: "Dashboard. Métricas. Proyección de ventas. Toma de desiciones.",
    sales_process: "Proceso de ventas",
    sales_closing: "Cierre de venta",
    payment_registration: "Imputación pagos",
    procedure_assignment: "Asignación de trámite",
    folder_delivery: "Entrega de carpeta",
    pledge_management: "Gestión de Prendas",
    approval: "Aprobación",
    procedure_management: "Gestión de trámite",
    sales_closing_title: "Cierre de venta",
    sales_closing_desc: "Una vez realizado el acuerdo con el cliente se registra la venta en la plataforma incluyendo el alta del cliente.",
    payment_registration_title: "Imputación de pagos",
    payment_registration_desc: "Se registran los pagos (efectivo, cheque, etc.) y se da seguimiento hasta cancelar el total.",
    procedure_assignment_title: "Asignación de trámite",
    procedure_assignment_desc: "Se asigna el trámite a gestoría.",
    folder_delivery_title: "Entrega de carpeta",
    folder_delivery_desc: "Gestoría retira el tramite y se hace la entrega del vehículo y carpeta al cliente.",
    pledge_management_title: "Gestion de Prendas",
    pledge_management_desc: "Si el cliente solicita crédito prendario, se cargan todos los datos que serán enviados a las entidades financieras.",
    approval_title: "Aprobación",
    approval_desc: "La gerencia se asegura que todo en la transacción esté correcto para su aprobación.",
    procedure_management_title: "Gestión de trámite",
    procedure_management_desc: "Se ingresa el tramite al registro y se da seguimiento.",

    about_us_title: "Quiénes somos",
    about_us_desc_1: "En Lutente Cloud, ayudamos a empresas y emprendedores a gestionar su negocio de manera eficiente con una plataforma en la nube fácil de usar, segura y accesible.",
    about_us_desc_2: "Desde 2013, hemos trabajado con diversas industrias, optimizando su cadena de suministro y mejorando su control operativo. Nuestro fundador, con más de 25 años de experiencia, ha asesorado a empresas en todo el mundo. Su formación en Ingeniería Electrónica en la Universidad Internacional de Florida (FIU), sumada a su Maestría en Administración de Empresas (MBA) en la Universidad de Duke, le ha permitido combinar conocimiento técnico con visión estratégica para crear una solución que realmente impacte en la productividad y rentabilidad de nuestros clientes.",
    about_us_desc_3: "Con Lutente Cloud, puedes  controlar ventas, stock, facturación y más, desde cualquier lugar. Ya sea con una compra única o una suscripción mensual, nuestra plataforma está diseñada para hacer más simple la gestión de tu empresa.",
    about_us_desc_4: "Si querés dejar atrás los métodos tradicionales y llevar tu negocio al siguiente nivel, Lutente Cloud es la herramienta que estabas buscando.",
    choose_next_level: "Elige llevar tu negocio al siguiente nivel.",
    our_vision: "Nuestra Visión",
    vision_text: "Es convertirnos en el aliado tecnológico preferido de las pequeñas y medianas empresas, proporcionando herramientas innovadoras que impulsen su crecimiento y eficiencia operativa. Deseamos que cada empresa pueda alcanzar su máximo potencial, simplificando procesos y tomando decisiones estratégicas utilizando tecnología de vanguardia con inteligencia artificial. Juntos, hacemos posible lo extraordinario",
    our_mission: "Nuestra Misión",
    mission_text: "Es transformar la gestión de las PYMEs a través de soluciones tecnológicas accesibles, fáciles de usar y altamente personalizables. Automatizamos procesos, optimizamos recursos y te ayudamos a mantener el control total de tu empresa. Empoderamos a emprendedores y empresarios, simplificando su día a día para que se concentren en lo que realmente importa: ¡hacer crecer su negocio!. Lutente Cloud: tu herramienta para crecer sin límites.",
    make_difference: "MARCAMOS LA DIFERENCIA",
    diff_1: "Te escuchamos, entendemos y acompañamos",
    diff_2: "Nos enfocamos en tus necesidades",
    diff_3: "Simplicidad y Eficiencia",
    diff_4: "Un equipo comprometido",
    diff_5: "Porque TU éxito es NUESTRO éxito",
    diff_6: "Conexión real, soluciones reales",

    name_placeholder: "Nombre",
    company_placeholder: "Empresa/Negocio (opcional)",
    number_placeholder: "Número (opcional)",
    email_placeholder: "Email",
    comments_placeholder: "Comentario (opcional)",
    submit_button: "Enviar",
    close_modal: "Cerrar",
    contact_us: "Contáctenos",
    copyright: "®Lutente 2023"
},

    en: {
        
        home: "Home",
        products: "Products",
        erp_pymes: "ERP SMEs",
        erp_vehicles: "ERP Vehicles",
        about_us: "About us",
        contact: "Contact",
        register: "Register",
        login: "Login",
        hero_title: "<strong>Lutente ERP</strong> is",
        hero_subtitle: "the solution you <strong>NEED</strong>",
        learn_more: "Learn more",
        section_1_title: "Your entire company in a single Management System",
        section_1_subtitle: "Our cloud-based management system is designed to simplify and optimize your company's operations.",
        section_2_title: "IT'S TIME TO GET OUR ERP",
        centralize_data: "CENTRALIZE YOUR DATA",
        centralize_text: "With an ERP, all the crucial information of your business (inventories, finances, sales, etc.) will be integrated into a single system, facilitating access and data analysis.",
        optimize_processes: "OPTIMIZE YOUR PROCESSES",
        optimize_text: "The automated functions of an ERP handle tedious tasks, allowing you to focus on growing your business.",
        increase_efficiency: "INCREASE EFFICIENCY",
        efficiency_text: "By eliminating manual procedures and human errors, an ERP will drastically increase your operational productivity.",
        reasons_to_choose_us: "REASONS TO CHOOSE US",
        global_access: "GLOBAL AND INSTANT ACCESS",
        global_access_text: "THE CLOUD ALLOWS YOU TO ACCESS YOUR DATA REMOTELY, GIVING YOU THE FREEDOM TO WORK FROM HOME, WHILE TRAVELING, OR EVEN FROM DIFFERENT LOCATIONS, WITH REAL-TIME UPDATED INFORMATION.",
        security: "DATA SECURITY AND PROTECTION",
        security_text: "BY UPDATING THE CLOUD PLATFORM YOU CAN BE SURE THAT YOUR DATA IS ROBUSTLY PROTECTED, SAFEGUARDED AGAINST LOSSES, THEFT OR INCONVENIENCES THANKS TO DAILY BACKUPS OF ALL INFORMATION.",
        scalability: "SCALABILITY AND FLEXIBILITY",
        scalability_text: "WITH THIS TOOL YOU CAN EASILY SCALE YOUR RESOURCES ACCORDING TO YOUR BUSINESS DEMAND. IF YOUR BUSINESS GROWS, YOU CAN SIMPLY EXPAND STORAGE AND PROCESSING CAPACITY IN THE CLOUD, WITHOUT THE NEED TO ACQUIRE NEW HARDWARE OR MAKE COSTLY UPGRADES.",
        cost_reduction: "COST REDUCTION",
        cost_reduction_text: "IMPLEMENTING THE PLATFORM IN THE CLOUD CAN GENERATE SIGNIFICANT COST SAVINGS. YOU WON'T HAVE TO INVEST IN EXPENSIVE SERVERS, OR THEIR DAILY MAINTENANCE. YOU WON'T NEED TO MANUALLY COPY DATA PERIODICALLY EITHER.",
        automotive_solution: "Automotive Solution",
        lutente_cars: "Lutente Cars",
        car_solution_text: "The management system aimed at dealerships and vehicle agencies.",
        contact_us: "Contact us",
        
        hero_title_erp: "Lutente ERP",
        hero_subtitle_erp: "Your entire company in a single Management System",
        request_demo: "Request DEMO",
        our_modules: "Our Modules",
        analytics: "ANALYTICS",
        analytics_desc: "Monitor sales, costs, and performance in real-time.",
        inventory: "INVENTORY",
        inventory_desc: "Maintain a precise and up-to-date control of your stock.",
        administration: "ADMINISTRATION",
        administration_desc: "Automate tasks and optimize the operational processes of your company.",
        purchases: "PURCHASES",
        purchases_desc: "Manage your purchase orders quickly and easily.",
        sales: "SALES",
        sales_desc: "Manage the entire sales process from one place.",
        optimize_company: "Optimize your company with our <strong>ERP</strong>.",
        system_description: "Our system is Modern, User-Friendly, and Optimized for maximum performance.",
        benefits: "<strong>BENEFITS</strong>",
        benefit_1_erp: "Data digitization and centralization.",
        benefit_2_erp: "Control and automation of transactions and cash flow.",
        benefit_3_erp: "Immediate electronic invoicing.",
        benefit_4_erp: "Integrations with online stores.",
        benefit_5_erp: "Expense categorization and accounting entries.",
        benefit_6_erp: "Personalized support and advice.",
        benefit_7_erp: "Better user experience.",

        benefit_1_cons: "✔ Data digitization and centralization.",
        benefit_2_cons: "✔ Control and automation of transactions and cash flow.",
        benefit_3_cons: "✔ Immediate electronic invoicing.",
        benefit_4_cons: "✔ Integrations with online stores.",
        benefit_5_cons: "✔ Expense categorization and accounting entries.",
        benefit_6_cons: "✔ Personalized support and advice.",
        benefit_7_cons: "✔ Better user experience.",
        digital_transformation: "Evolve your company with a <strong>Digital Transformation</strong>.",
        improve_business: "Improve your business",
        cloud_benefits: "Lutente Cloud allows you to manage operations EFFICIENTLY and SIMPLY, using AI to maximize YOUR company's growth",
        copyright: "®Lutente 2023",

        lutente_cloud_desc: "Lutente Cloud allows dealerships and vehicle agencies to manage all areas of the company with greater efficiency and speed.",
        request_demo: "Request DEMO",
        enter_demo: "Enter DEMO",
        modules: "Modules",
        benefits: "Benefits",
        benefit_1: " Visibility and decision-making",
        benefit_2: " Digitization and data centralization",
        benefit_3: " Management: inventory, sales, pledges, customers, suppliers, procedures, and expenses",
        benefit_4: " Control and automation of movements and cash flow",
        benefit_5: " Control of cash flow, checks, and promissory notes",
        benefit_6: " Better customer experience",

        lutente_cloud_desc: "Lutente Cloud allows dealerships and vehicle agencies to manage all areas of the company with greater efficiency and speed.",
    request_demo: "Request DEMO",
    enter_demo: "Enter DEMO",
    modules: "Modules",
    inventory_module: "INVENTORY",
    inventory_desc: "Vehicle inventory. Integration with InfoAutos. Easy entry/exit. Easy price updates.",
    sales_module: "SALES",
    sales_desc: "Sales Closure and History. Pledge Credits. Customers.",
    admin_module: "ADMINISTRATION",
    admin_desc: "After-sales tracking. Cash. Suppliers. Transactions/Movements. Assignment of procedures. Expenses.",
    registry_module: "REGISTRY",
    registry_desc: "Procedures. Reception. Preparation. Administration presentation. Tracking. Withdrawal and closure.",
    analytics_module: "ANALYTICS",
    analytics_desc: "Dashboard. Metrics. Sales projections. Decision making.",
    sales_process: "Sales process",
    sales_closing: "Sales closing",
    payment_registration: "Payment registration",
    procedure_assignment: "Procedure assignment",
    folder_delivery: "Folder delivery",
    pledge_management: "Pledge management",
    approval: "Approval",
    procedure_management: "Procedure management",
    sales_closing_title: "Sales closing",
    sales_closing_desc: "Once the agreement with the customer is made, the sale is registered in the platform including the customer registration.",
    payment_registration_title: "Payment registration",
    payment_registration_desc: "Payments (cash, check, etc.) are registered and tracked until the total is canceled.",
    procedure_assignment_title: "Procedure assignment",
    procedure_assignment_desc: "The procedure is assigned to the registry office.",
    folder_delivery_title: "Folder delivery",
    folder_delivery_desc: "Registry office withdraws the procedure and the vehicle and folder are delivered to the customer.",
    pledge_management_title: "Pledge management",
    pledge_management_desc: "If the customer requests pledge credit, all data that will be sent to financial entities is loaded.",
    approval_title: "Approval",
    approval_desc: "Management ensures that everything in the transaction is correct for approval.",
    procedure_management_title: "Procedure management",
    procedure_management_desc: "The procedure is entered into the registry and followed up.",

    about_us_title: "Who we are",
    about_us_desc_1: "At Lutente Cloud, we help businesses and entrepreneurs efficiently manage their business with an easy-to-use, secure, and accessible cloud platform.",
    about_us_desc_2: "Since 2013, we have worked with various industries, optimizing their supply chain and improving their operational control. Our founder, with over 25 years of experience, has advised companies worldwide. His education in Electronic Engineering at Florida International University (FIU), combined with his Master's in Business Administration (MBA) from Duke University, has allowed him to combine technical knowledge with strategic vision to create a solution that truly impacts our clients' productivity and profitability.",
    about_us_desc_3: "With Lutente Cloud, you can control sales, inventory, billing, and more from anywhere. Whether with a one-time purchase or a monthly subscription, our platform is designed to simplify the management of your company.",
    about_us_desc_4: "If you want to leave traditional methods behind and take your business to the next level, Lutente Cloud is the tool you've been looking for.",choose_next_level: "Choose to take your business to the next level.",
    our_vision: "Our Vision",
    vision_text: "We aim to become the preferred technological ally of small and medium-sized companies, providing innovative tools that drive their growth and operational efficiency. We want each company to reach its maximum potential, simplifying processes and making strategic decisions using cutting-edge technology with artificial intelligence. Together, we make the extraordinary possible.",
    our_mission: "Our Mission",
    mission_text: "Our mission is to transform SME management through accessible, easy-to-use, and highly customizable technological solutions. We automate processes, optimize resources, and help you maintain total control of your company. We empower entrepreneurs and business owners, simplifying their daily operations so they can focus on what really matters: growing their business! Lutente Cloud: your tool to grow without limits.",
    make_difference: "WE MAKE THE DIFFERENCE",
    diff_1: "We listen, understand, and support you",
    diff_2: "We focus on your needs",
    diff_3: "Simplicity and Efficiency",
    diff_4: "A committed team",
    diff_5: "Because YOUR success is OUR success",
    diff_6: "Real connection, real solutions",

    name_placeholder: "Name",
    company_placeholder: "Company/Business (optional)",
    number_placeholder: "Phone Number (optional)",
    email_placeholder: "Email",
    comments_placeholder: "Comments (optional)",
    submit_button: "Send",
    close_modal: "Close",
    contact_us: "Contact us",
    copyright: "®Lutente 2023"
    }
};