const languages = {
    es: {
        home: "Inicio",
        products: "Productos",
        erp_pymes: "ERP PyMEs",
        erp_vehicles: "ERP Vehículos",
        about_us: "Sobre nosotros",
        contact: "Contacto",
        register: "Registro",
        login: "Ingreso",
        hero_title: "<strong>Lutente ERP</strong> es",
        hero_subtitle: "La solución que <strong>NECESITAS</strong>",
        learn_more: "Conocer más",
        section_1_title: "Toda tu empresa en un solo Sistema de Gestión",
        section_1_subtitle: "Nuestro sistema de gestión en la nube está diseñado para simplificar y optimizar la operación de tu empresa.",
        section_2_title: "ES HORA DE ADQUIRIR NUESTRO ERP",
        centralize_data: "CENTRALIZA TUS DATOS",
        centralize_text: "Con un ERP, toda la información crucial de tu negocio (inventarios, finanzas, ventas, etc.) estará integrada en un solo sistema, ¡facilitando el acceso y análisis de datos!.",
        optimize_processes: "OPTIMIZA TUS PROCESOS",
        optimize_text: "Las funciones automatizadas de un ERP se encargan de las tareas tediosas, permitiéndote concentrarse en el crecimiento de su negocio.",
        increase_efficiency: "AUMENTA LA EFICIENCIA",
        efficiency_text: "Al eliminar procedimientos manuales y errores humanos, un ERP aumentará drásticamente la productividad de tus operaciones.",
        reasons_to_choose_us: "4 RAZONES PARA ELEGIRNOS",
        global_access: "ACCESO GLOBAL E INSTANTÁNEO",
        global_access_text: "LA NUBE TE PERMITE ACCEDER A TUS DATOS DE FORMA REMOTA, LO QUE TE BRINDA LA LIBERTAD DE TRABAJAR DESDE CASA, MIENTRAS VIAJAS, O INCLUSO DE DIFERENTES UBICACIONES, CON INFORMACIÓN ACTUALIZADA EN TIEMPO REAL.",
        security: "SEGURIDAD Y PROTECCIÓN DE DATOS",
        security_text: "AL ACTUALIZAR LA PLATAFORMA EN LA NUBE PUEDES ESTAR TRANQUILO SABIENDO QUE TUS DATOS ESTÁN PROTEGIDOS DE FORMA ROBUSTA.",
        scalability: "ESCALABILIDAD Y FLEXIBILIDAD",
        scalability_text: "CON ESTA HERRAMIENTA PUEDES ESCALAR FÁCILMENTE TUS RECURSOS SEGÚN LA DEMANDA DE TU EMPRESA.",
        cost_reduction: "REDUCCIÓN DE COSTOS",
        cost_reduction_text: "LA IMPLEMENTACIÓN DE LA PLATAFORMA EN LA NUBE PUEDE GENERAR AHORROS SIGNIFICATIVOS DE COSTOS.",
        automotive_solution: "Solución Automotor",
        lutente_cars: "Lutente Autos",
        car_solution_text: "El sistema de gestión orientado a concesionarias y agencias de vehículos.",
        contact_us: "Contáctenos"
    },
    en: {
        home: "Home",
        products: "Products",
        erp_pymes: "ERP SMEs",
        erp_vehicles: "ERP Vehicles",
        about_us: "About us",
        contact: "Contact",
        register: "Register",
        login: "Login",
        hero_title: "<strong>Lutente ERP</strong> is",
        hero_subtitle: "The solution you <strong>NEED</strong>",
        learn_more: "Learn more",
        section_1_title: "Your entire company in a single Management System",
        section_1_subtitle: "Our cloud-based management system is designed to simplify and optimize your company's operations.",
        section_2_title: "IT'S TIME TO GET OUR ERP",
        centralize_data: "CENTRALIZE YOUR DATA",
        centralize_text: "With an ERP, all the crucial information of your business (inventories, finances, sales, etc.) will be integrated into a single system, facilitating access and data analysis.",
        optimize_processes: "OPTIMIZE YOUR PROCESSES",
        optimize_text: "The automated functions of an ERP handle tedious tasks, allowing you to focus on growing your business.",
        increase_efficiency: "INCREASE EFFICIENCY",
        efficiency_text: "By eliminating manual procedures and human errors, an ERP will drastically increase your operational productivity.",
        reasons_to_choose_us: "4 REASONS TO CHOOSE US",
        global_access: "GLOBAL AND INSTANT ACCESS",
        global_access_text: "THE CLOUD ALLOWS YOU TO ACCESS YOUR DATA REMOTELY, GIVING YOU THE FREEDOM TO WORK FROM HOME, WHILE TRAVELING, OR EVEN FROM DIFFERENT LOCATIONS, WITH REAL-TIME UPDATED INFORMATION.",
        security: "DATA SECURITY AND PROTECTION",
        security_text: "BY UPDATING THE CLOUD PLATFORM YOU CAN BE SURE THAT YOUR DATA IS ROBUSTLY PROTECTED.",
        scalability: "SCALABILITY AND FLEXIBILITY",
        scalability_text: "WITH THIS TOOL YOU CAN EASILY SCALE YOUR RESOURCES ACCORDING TO YOUR BUSINESS DEMAND.",
        cost_reduction: "COST REDUCTION",
        cost_reduction_text: "IMPLEMENTING THE PLATFORM IN THE CLOUD CAN GENERATE SIGNIFICANT COST SAVINGS.",
        automotive_solution: "Automotive Solution",
        lutente_cars: "Lutente Cars",
        car_solution_text: "The management system aimed at dealerships and vehicle agencies.",
        contact_us: "Contact us"
    }
};
